include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = IslandBatteryNotchPrefs
IslandBatteryNotchPrefs_FILES = IBNRootListController.m
IslandBatteryNotchPrefs_CFLAGS = -fobjc-arc -Wall -Wextra -Wno-unused-parameter
IslandBatteryNotchPrefs_FRAMEWORKS = UIKit Foundation CoreFoundation
IslandBatteryNotchPrefs_PRIVATE_FRAMEWORKS = Preferences
IslandBatteryNotchPrefs_INSTALL_PATH = /Library/PreferenceBundles
IslandBatteryNotchPrefs_INFOPLIST_FILE = Resources/Info.plist

include $(THEOS_MAKE_PATH)/bundle.mk
